/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amir' at '3/9/16 11:21 AM' with Gradle 2.10
 *
 * @author amir, @date 3/9/16 11:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
